[package]
name = "qreeper_decoder"
version = "0.1.0"
edition = "2018"

[dependencies]
gtk = "0.9.0"
gio = "0.9.0"
glib = "0.10.0"
qrcode = "0.12.0"
flate2 = "1.0.20"
data-encoding = "2.3.2"
image = "0.23.14"
hex = "0.4.3"
rqrr = "0.3.0"